### ISSUE TITLE
Dates?

### ISSUE THREAD

**Issue by tomcardoso** [onyxfish/lookup#15]
I was just grabbing this month's [Canadian house price index data](www.housepriceindex.ca/), and of course they decided to encode their dates like this:

| Date | Index |
| --- | --- |
| Jan-2015 | 167.110 |
| Feb-2015 | 167.320 |
| Mar-2015 | 167.830 |
| Apr-2015 | 168.090 |
| May-2015 | 169.750 |
| Jun-2015 | 172.220 |
| Jul-2015 | 174.530 |
| Aug-2015 | 176.590 |
| Sep-2015 | 177.760 |
| Oct-2015 | 177.960 |
| Nov-2015 | 178.350 |
| Dec-2015 | 178.260 |
| Jan-2016 | 178.010 |
| Feb-2016 | 179.200 |

It'd be nice to be able to automatically re-encode these to ISO 8601. Would this be a good application of lookup? There's bound to be some variation in how the months are abbreviated, so I'm not entirely sure. Also, days of the month might not always be in the dataset…

**Comment by onyxfish** [comment]
Hmm, that doesn't seem like a case for lookup because:
1. The solution is easy to accomplish programmatically, by parsing the data and reformatting it.
2. The possible range to be mapped sequence is unbounded.

That being said, if you wanted to reformat the dates as year and month columns the price sequence itself would make a great lookup table!

**Comment by jpmckinney** [comment]
Agreed – I don't think mapping an infinite codelist is a use case for lookup.
